site_name: Requisitos de Software - Shazam
repo_name: 'Requisitos2-2019/Shazam'
repo_url: 'https://github.com/Requisitos2-2019/2019.2-Shazam'
site_description: 'Requisitos de Software do aplicativo Shazam'

nav:
  - Home: 'index.md'
  - Pr√©-Rastreabilidade:
    - Rich Pictures: 'pre-rastreabilidade/rich-pictures/index.md'

theme:
  name: 'material'
  palette:
    accent: 'indigo'
    # primary: '#08f'
  logo: 'assets/img/shazam-logo.png'
  favicon: 'assets/img/favicon.ico'
  language: 'pt'


extra_css:
    - css/extra.css